package com.mycompany.calculadora;

import java.util.logging.Level;
import java.util.logging.Logger;

public class jfrmCalc2 extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(jfrmCalc2.class.getName());

    
    private String entrada = "";
    private double numero1, numero2;
    private String operador = "";

    public jfrmCalc2() {
        initComponents();
        aplicarColores();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jtbn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jtbn3 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnborrar = new javax.swing.JButton();
        jbtndivi = new javax.swing.JButton();
        jbtnigual = new javax.swing.JButton();
        jbtnmulti = new javax.swing.JButton();
        jbtnresta = new javax.swing.JButton();
        jbtnsuma = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jtbnPunto = new javax.swing.JButton();
        jtbnRaiz = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jtbnPorcentaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(this::jbtn7ActionPerformed);

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(this::jbtn9ActionPerformed);

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(this::jbtn8ActionPerformed);

        jtbn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbn4.setText("4");
        jtbn4.addActionListener(this::jtbn4ActionPerformed);

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(this::jbtn5ActionPerformed);

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(this::jbtn6ActionPerformed);

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(this::jbtn2ActionPerformed);

        jtbn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbn3.setText("3");
        jtbn3.addActionListener(this::jtbn3ActionPerformed);

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(this::jbtn1ActionPerformed);

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(this::jbtn0ActionPerformed);

        jbtnborrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnborrar.setText("AC");
        jbtnborrar.addActionListener(this::jbtnborrarActionPerformed);

        jbtndivi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndivi.setText("/");
        jbtndivi.addActionListener(this::jbtndiviActionPerformed);

        jbtnigual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnigual.setText("=");
        jbtnigual.addActionListener(this::jbtnigualActionPerformed);

        jbtnmulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnmulti.setText("X");
        jbtnmulti.addActionListener(this::jbtnmultiActionPerformed);

        jbtnresta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnresta.setText("-");
        jbtnresta.addActionListener(this::jbtnrestaActionPerformed);

        jbtnsuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(this::jbtnsumaActionPerformed);

        jtxtCantidad.setText("                 ");

        jtbnPunto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbnPunto.setText(".");
        jtbnPunto.addActionListener(this::jtbnPuntoActionPerformed);

        jtbnRaiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbnRaiz.setText("√");
        jtbnRaiz.addActionListener(this::jtbnRaizActionPerformed);

        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(this::jbtnCActionPerformed);

        jtbnPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtbnPorcentaje.setText("%");
        jtbnPorcentaje.addActionListener(this::jtbnPorcentajeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCantidad)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtn1)
                                            .addComponent(jtbn4))
                                        .addGap(27, 27, 27)
                                        .addComponent(jbtn5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtn2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtbn3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtn7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtn8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnresta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnmulti, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtndivi, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnborrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnigual)
                                .addGap(14, 14, 14)
                                .addComponent(jbtnsuma)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbnPunto)
                            .addComponent(jtbnPorcentaje)
                            .addComponent(jbtnC)
                            .addComponent(jtbnRaiz))))
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndivi)
                    .addComponent(jbtn7)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jtbnPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnmulti)
                    .addComponent(jtbn4)
                    .addComponent(jbtn6)
                    .addComponent(jbtn5)
                    .addComponent(jtbnPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnresta)
                        .addComponent(jtbn3)
                        .addComponent(jtbnRaiz))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn1)
                        .addComponent(jbtn2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnsuma)
                    .addComponent(jbtnigual)
                    .addComponent(jbtnborrar)
                    .addComponent(jbtn0)
                    .addComponent(jbtnC))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "7";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "9";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "8";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jtbn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "4";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jtbn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "5";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "6";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "2";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jtbn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "3";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jtbn3ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "1";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + "0";
        jtxtCantidad.setText(entrada);

    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborrarActionPerformed
        // TODO add your handling code here:
    entrada = "";
    numero1 = 0;
    numero2 = 0;
    operador = "";
    jtxtCantidad.setText("0");
    }//GEN-LAST:event_jbtnborrarActionPerformed

    private void jbtndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndiviActionPerformed
        // TODO add your handling code here:
           if (entrada.equals("") == false) {
        if (operador.equals("") == false) {
            numero2 = Double.parseDouble(entrada);
            double resultado = 0;
            if (operador.equals("+")) { resultado = numero1 + numero2; }
            else if (operador.equals("-")) { resultado = numero1 - numero2; }
            else if (operador.equals("*")) { resultado = numero1 * numero2; }
            else if (operador.equals("/")) { resultado = numero1 / numero2; }
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            numero1 = resultado;
        } else {
            numero1 = Double.parseDouble(entrada);
        }
        operador = "/";   
        entrada = "";
        jtxtCantidad.setText("");
}
    }//GEN-LAST:event_jbtndiviActionPerformed

    private void jbtnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnigualActionPerformed
        // TODO add your handling code here:
        numero2=Double.parseDouble(entrada);
        jtxtCantidad.setText("");
        entrada= "";
        double resultado;
        if (operador.equals("+")){
            resultado= numero1+numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("-")){
            resultado= numero1-numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("*")){
            resultado= numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("/")){
            resultado= numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnigualActionPerformed
    }
    private void jbtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiActionPerformed
        // TODO add your handling code here:
           if (entrada.equals("") == false) {
        if (operador.equals("") == false) {
            numero2 = Double.parseDouble(entrada);
            double resultado = 0;
            if (operador.equals("+")) { resultado = numero1 + numero2; }
            else if (operador.equals("-")) { resultado = numero1 - numero2; }
            else if (operador.equals("*")) { resultado = numero1 * numero2; }
            else if (operador.equals("/")) { resultado = numero1 / numero2; }
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            numero1 = resultado;
        } else {
            numero1 = Double.parseDouble(entrada);
        }
        operador = "*";   
        entrada = "";
        jtxtCantidad.setText("");
}
    }//GEN-LAST:event_jbtnmultiActionPerformed

    private void jbtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestaActionPerformed
        // TODO add your handling code here:
           if (entrada.equals("") == false) {
        if (operador.equals("") == false) {
            numero2 = Double.parseDouble(entrada);
            double resultado = 0;
            if (operador.equals("+")) { resultado = numero1 + numero2; }
            else if (operador.equals("-")) { resultado = numero1 - numero2; }
            else if (operador.equals("*")) { resultado = numero1 * numero2; }
            else if (operador.equals("/")) { resultado = numero1 / numero2; }
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            numero1 = resultado;
        } else {
            numero1 = Double.parseDouble(entrada);
        }
        operador = "-";   
        entrada = "";
        jtxtCantidad.setText("");
}
    }//GEN-LAST:event_jbtnrestaActionPerformed

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        // TODO add your handling code here:
        //CAPTURAR Y CONVERTIR EL TEXTO A UN VALOR
        //LIMPIAR LA CAJA DE TEXTO
        //CPATURAR EL SIGNO= OPERAR
        //ENVIAR EN PANTALÑAÑP LO QUE CAPTURADO EN ENTRADA 
        if (entrada.equals("") == false) {
        if (operador.equals("") == false) {
            numero2 = Double.parseDouble(entrada);
            double resultado = 0;
            if (operador.equals("+")) { resultado = numero1 + numero2; }
            else if (operador.equals("-")) { resultado = numero1 - numero2; }
            else if (operador.equals("*")) { resultado = numero1 * numero2; }
            else if (operador.equals("/")) { resultado = numero1 / numero2; }
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            numero1 = resultado;
        } else {
            numero1 = Double.parseDouble(entrada);
        }
        operador = "+";   
        entrada = "";
        jtxtCantidad.setText("");
}
    }//GEN-LAST:event_jbtnsumaActionPerformed

    private void jtbnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnPuntoActionPerformed
        // TODO add your handling code here:
         if (entrada.contains(".") == false) {
        if (entrada.equals("")) {
            entrada = "0.";
        } else {
            entrada = entrada + ".";
        }
        jtxtCantidad.setText(entrada);
         }
    }//GEN-LAST:event_jtbnPuntoActionPerformed

    private void jtbnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnPorcentajeActionPerformed
        // TODO add your handling code here:
         if (entrada.equals("") == false) {
        double valor = Double.parseDouble(entrada);
        double resultado = valor / 100;
        entrada = String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jtbnPorcentajeActionPerformed

    private void jtbnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnRaizActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(jtxtCantidad.getText());
    if (valor >= 0) {
        valor = Math.sqrt(valor);
        entrada = String.valueOf(valor);
        jtxtCantidad.setText(entrada);
    } else {
        jtxtCantidad.setText("Error");
        entrada = "";
    }
    }//GEN-LAST:event_jtbnRaizActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
         String texto = jtxtCantidad.getText();
    if (texto.length() > 1) {
        texto = texto.substring(0, texto.length() - 1);
        entrada = texto;
        jtxtCantidad.setText(texto);
    } else {
        jtxtCantidad.setText("0");
        entrada = "";
    }
    }//GEN-LAST:event_jbtnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalc2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnborrar;
    private javax.swing.JButton jbtndivi;
    private javax.swing.JButton jbtnigual;
    private javax.swing.JButton jbtnmulti;
    private javax.swing.JButton jbtnresta;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JButton jtbn3;
    private javax.swing.JButton jtbn4;
    private javax.swing.JButton jtbnPorcentaje;
    private javax.swing.JButton jtbnPunto;
    private javax.swing.JButton jtbnRaiz;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables

    private void aplicarColores() {
    
// Fondo
    getContentPane().setBackground(new java.awt.Color(18, 18, 18));

    // Pantalla
    jtxtCantidad.setBackground(java.awt.Color.BLACK);
    jtxtCantidad.setForeground(new java.awt.Color(0, 255, 180));

    // Botones numéricos (azul intenso)
    java.awt.Color numColor = new java.awt.Color(33, 150, 243);
    java.awt.Color txtColor = java.awt.Color.WHITE;

    jbtn0.setBackground(numColor);
    jbtn1.setBackground(numColor);
    jbtn2.setBackground(numColor);
    jtbn3.setBackground(numColor);
    jtbn4.setBackground(numColor);
    jbtn5.setBackground(numColor);
    jbtn6.setBackground(numColor);
    jbtn7.setBackground(numColor);
    jbtn8.setBackground(numColor);
    jbtn9.setBackground(numColor);

    jbtn0.setForeground(txtColor);
    jbtn1.setForeground(txtColor);
    jbtn2.setForeground(txtColor);
    jtbn3.setForeground(txtColor);
    jtbn4.setForeground(txtColor);
    jbtn5.setForeground(txtColor);
    jbtn6.setForeground(txtColor);
    jbtn7.setForeground(txtColor);
    jbtn8.setForeground(txtColor);
    jbtn9.setForeground(txtColor);

    // Operaciones (morado)
    java.awt.Color opColor = new java.awt.Color(156, 39, 176);

    jbtnsuma.setBackground(opColor);
    jbtnresta.setBackground(opColor);
    jbtnmulti.setBackground(opColor);
    jbtndivi.setBackground(opColor);

    jbtnsuma.setForeground(txtColor);
    jbtnresta.setForeground(txtColor);
    jbtnmulti.setForeground(txtColor);
    jbtndivi.setForeground(txtColor);

    // Igual (verde neón)
    jbtnigual.setBackground(new java.awt.Color(0, 200, 83));
    jbtnigual.setForeground(txtColor);

    // Borrar (rojo fuerte)
    jbtnC.setBackground(new java.awt.Color(244, 67, 54));
    jbtnC.setForeground(txtColor);
}

    }